# Generated by Django 5.1.1 on 2024-09-20 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_country_capital'),
    ]

    operations = [
        migrations.AddField(
            model_name='capital',
            name='country_name',
            field=models.OneToOneField(default=' ', on_delete=django.db.models.deletion.CASCADE, to='app.country'),
        ),
        migrations.AlterField(
            model_name='capital',
            name='capital_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
