# Generated by Django 5.1.1 on 2024-09-20 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_emp_dno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dept',
            name='id',
        ),
        migrations.AlterField(
            model_name='dept',
            name='dno',
            field=models.PositiveIntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
