# Generated by Django 5.1.1 on 2024-09-20 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_dept_id_alter_dept_dno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emp',
            name='dno',
        ),
        migrations.DeleteModel(
            name='dept',
        ),
        migrations.DeleteModel(
            name='emp',
        ),
    ]
