# Generated by Django 5.1.1 on 2024-09-20 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_dept_emp'),
    ]

    operations = [
        migrations.AddField(
            model_name='dept',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dept',
            name='dno',
            field=models.PositiveIntegerField(auto_created=True),
        ),
    ]
