# Generated by Django 5.1.1 on 2024-10-11 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('pid', models.IntegerField(primary_key=True, serialize=False)),
                ('pname', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=3, max_digits=10)),
                ('manufacture', models.CharField(max_length=100)),
                ('mdate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategoryies',
            fields=[
                ('pcid', models.IntegerField(primary_key=True, serialize=False)),
                ('product_category_name', models.CharField(max_length=100)),
                ('source', models.CharField(max_length=100)),
            ],
        ),
    ]
