# Generated by Django 5.1.1 on 2024-10-11 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pcid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.productcategoryies'),
        ),
    ]
