# Generated by Django 5.1.2 on 2024-11-08 09:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='allinone',
            name='text',
            field=models.CharField(default=None, max_length=100, validators=[django.core.validators.EmailValidator()]),
        ),
    ]
